services:
  - type: web
    name: rutasegura-api
    env: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    rootDir: .
    healthCheckPath: /swagger
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/tmp/rutasegura.db
      - key: Jwt__Issuer
        value: RutaSegura.API
      - key: Jwt__Audience
        value: RutaSegura.Client
      - key: Jwt__Key
        generateValue: true
      - key: Redis__ConnectionString
        value: redis://default:ES5tBWfe6Oyg08VT3E3EZDKqXX1DQ5EL@redis-14083.c98.us-east-1-4.ec2.cloud.redislabs.com:14083
      - key: FRONTEND_URL
        value: https://rutasegura-frontend.onrender.com

  - type: web
    name: rutasegura-frontend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_GOOGLE_MAPS_API_KEY
        value: tu_google_maps_key
      - key: VITE_API_URL
        value: https://rutasegura-api.onrender.com
