services:
  - type: web
    name: rutasegura-api
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    rootDir: .
    healthCheckPath: /swagger
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/var/data/rutasegura.db
      - key: Jwt__Issuer
        value: RutaSegura.API
      - key: Jwt__Audience
        value: RutaSegura.Client
      - key: Jwt__Key
        generateValue: true
      - key: Redis__ConnectionString
        fromService:
          name: rutasegura-redis
          type: redis
          property: connectionString
    disks:
      - name: rutasegura-data
        mountPath: /var/data
        sizeGB: 1

  - type: redis
    name: rutasegura-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
